/////////////////////////////////////////////////////////////////////////////
export const projectData = [
  {
    // src: `https://booking-app-v2.onrender.com/logo-dark.png`,
    src: `/logo-green-round.png`,
    alt: "Dev Blog Platform",
    h3: " A community for developers to share knowledge and grow together. (FullStack APP)",
    p: "A portfolio project to demonstrate my fullstack skills.",
    span1: "Tech stack: Next.js (App Router), Tailwind, React Query",
    span2: "Database: MongoDB (Atlas) with Mongoose",
    span3: "Dev Tools: Nodemon, dotenv, Postman, ESLint, Prettier",
    span4:
      "Protected routes, dynamic metadata, and image optimization with Next.js",
    hrefDemo: "https://dev-blog-frontend-v1-Kruh.vercel.app",
    hrefCode: "https://github.com/Whiz225/dev-blog-frontend-v1",
  },
  {
    src: `https://booking-app-v2.onrender.com/logo-dark.png`,
    alt: "Tour Booking Platform",
    h3: "A Cabin Booking Website for Guest (FullStack APP)",
    p: "A portfolio project to demonstrate my fullstack skills.",
    span1: "Tech stack: Next.js (App Router), Tailwind, React Context API",
    span2: "Database: MongoDB (Atlas) with Mongoose",
    span3: "Dev Tools: Nodemon, dotenv, Postman, ESLint, Prettier",
    span4:
      "Protected routes, dynamic metadata, and image optimization with Next.js",
    hrefDemo: "https://booking-app-v1-website.vercel.app",
    hrefCode: "https://github.com/Whiz225/Booking-app-Website",
  },
  {
    src: `https://booking-app-v2.onrender.com/logo-dark.png`,
    alt: "Tour Booking Platform",
    h3: "A Cabin Booking Management App (FullStack APP)",
    p: "A portfolio project to demonstrate my fullstack skills.",
    span1: "Frontend: React (Vite), Styled-components, React query",
    span2: "Backend: Node.js + Express.js, RESTful APIs",
    span3: "Database: MongoDB (Atlas) with Mongoose",
    span4: "Dev Tools: Nodemon, dotenv, Postman, ESLint, Prettier",
    hrefDemo: "https://booking-app-v2.onrender.com",
    hrefCode: "https://github.com/Whiz225/Booking-App",
  },
  {
    src: `https://natours-1-qn7z.onrender.com/img/tours/tour-2-cover.jpg`,
    alt: "Tour Booking Platform",
    h3: "Tour Booking Web App (Fullstack App)",
    p: "A portfolio project to demonstrate my fullstack skills.",
    span1:
      "Frontend: HTML, CSS (Sass), Pug (templating engine), client-side JS",
    span2: "Backend: Node.js, Express.js, RESTful APIs",
    span3: "Database: MongoDB with Mongoose ORM",
    span4: "Security: Helmet, Rate limiting, Data sanitization, etc",
    hrefDemo: "https://natours-1-qn7z.onrender.com",
    hrefCode: "https://github.com/Whiz225/Natours",
  },
  {
    src: `https://p-ventures.onrender.com/img%20copy/tours/tour-3-1.jpg`,
    alt: "Travel Tracking App",
    h3: "Travel Tracking App",
    p: "A portfolio project to demonstrate my frontend skills.",
    span1: "Frontend: React, Context API, Custom Hooks, CSS Modules",
    span2: "Map: React Leaflet",
    span3: "State: React Context + useReducer ",
    span4: "APIs: PositionStack (for geocoding), REST endpoints",
    hrefDemo: "https://worldwise-app-q75x.onrender.com",
    hrefCode: "https://github.com/Whiz225/Worldwise-app",
  },
  {
    src: `https://dclaevazetcjjkrzczpc.supabase.co/storage/v1/object/public/pizzas/pizza-1.jpg`,
    alt: "Fast React Pizza App",
    h3: "Fast React Pizza Co.",
    p: "A portfolio project to demonstrate my frontend skills.",
    span1: "Firebase",
    span2: "Frontend: React (Vite)/ HTML/ Tailwind CSS",
    span3: "State: Redux ToolKit",
    span4: "Router: React Router",
    hrefDemo: "https://fast-react-pizza-dxho.onrender.com",
    hrefCode: "https://github.com/Whiz225/Fast-react-pizza",
  },
  // {
  //   src: ``,
  //   alt: "",
  //   h3: "",
  //   p: "",
  //   span1: "",
  //   span2: "",
  //   span3: "",
  //   span4:
  //     "",
  //   href: "",
  //   hrefCode: "",
  // },
];
